#!/usr/bin/env bash
# Displays `Y U no love me?!` when receiving a SIGINT signal
# Deletes the file `/var/run/myscript.pid` and terminates itself when receiving a SIGQUIT or SIGTERM signal

trap "echo 'I hate the kill command'" SIGTERM
killer() {
    rm /var/run/myscript.pid
    exit 0
}

trap "echo 'I hate the kill command' && killer" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm /var/run/myscript.pid; exit 0" SIGQUIT SIGTERM
trap "killer" SIGQUIT
echo '$$' > /var/run/myscript.pid
while true
do

